AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 2.5

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleCopDisableDirective:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
